name: Batch Inference Pipeline

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - develop # Change to main

jobs:
  inference-pipeline:
    runs-on: ubuntu-latest  # Still points to Ubuntu 22.04 (as of mid-2025)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # <-- Change this line

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run inference pipeline
        run: PYTHONPATH=. python src/batch_inference/batch_inference_pipeline.py